"""Реестр правил сканирования: что ищем, зачем оно и насколько безопасно чистить."""
from __future__ import annotations

from dataclasses import dataclass, field


@dataclass(frozen=True)
class CacheRule:
    id: str
    group: str
    title: str
    risk: str  # Safe | Moderate | Advanced
    paths: list[str] = field(default_factory=list)
    what: str = ""
    why: str = ""
    safety: str = ""
    recommend: str = ""

    @property
    def risk_ru(self) -> str:
        return {"Safe": "Безопасно", "Moderate": "Умеренно", "Advanced": "Осторожно"}.get(self.risk, self.risk)


RISK_ORDER = {"Safe": 0, "Moderate": 1, "Advanced": 2}

RULES: list[CacheRule] = [
    # ---------------------------------------------------------------- GPU
    CacheRule(
        id="dx_shader",
        group="GPU и игры",
        title="DirectX Shader Cache",
        risk="Safe",
        paths=[r"%LOCALAPPDATA%\D3DSCache"],
        what="Скомпилированные шейдеры Direct3D. Windows и игры складывают сюда готовые варианты шейдеров, чтобы не компилировать их каждый запуск.",
        why="Создаётся автоматически при запуске игр и 3D-приложений. Со временем накапливаются версии от старых драйверов и удалённых игр.",
        safety="Удаление безопасно: кэш пересоздастся при следующем запуске игры. Возможна однократная микропауза/подгрузка шейдеров в первой сессии.",
        recommend="Можно чистить смело, особенно после обновления видеодрайвера.",
    ),
    CacheRule(
        id="nvidia_cache",
        group="GPU и игры",
        title="NVIDIA DXCache / GLCache / ComputeCache",
        risk="Safe",
        paths=[
            r"%LOCALAPPDATA%\NVIDIA\DXCache",
            r"%LOCALAPPDATA%\NVIDIA\GLCache",
            r"%LOCALAPPDATA%\NVIDIA\ComputeCache",
            r"%APPDATA%\NVIDIA\ComputeCache",
            r"%LOCALAPPDATA%\NVIDIA Corporation\NV_Cache",
            r"%PROGRAMDATA%\NVIDIA Corporation\NV_Cache",
        ],
        what="Шейдерные и ядерные кэши драйвера NVIDIA (DirectX, OpenGL, CUDA). Ускоряют запуск игр и GPU-вычислений.",
        why="Драйвер копит бинарники под каждую игру и версию драйвера. После обновления драйвера старые записи мёртвым грузом лежат месяцами.",
        safety="Безопасно. Драйвер пересоздаст нужное. Чистите после каждого обновления GeForce Driver.",
        recommend="Закройте игры и GPU-приложения перед очисткой.",
    ),
    CacheRule(
        id="amd_cache",
        group="GPU и игры",
        title="AMD Shader Cache (DxCache, DxcCache, GLCache)",
        risk="Safe",
        paths=[
            r"%LOCALAPPDATA%\AMD\DxCache",
            r"%LOCALAPPDATA%\AMD\DxcCache",
            r"%LOCALAPPDATA%\AMD\GLCache",
            r"%LOCALAPPDATA%\AMD\VkCache",
        ],
        what="Аналог NVIDIA-кэша для видеокарт AMD: скомпилированные шейдеры DX/Vulkan/OpenGL.",
        why="Накапливается от разных игр и версий Adrenalin.",
        safety="Безопасно, пересоздаётся автоматически.",
        recommend="Чистить после обновления драйвера AMD.",
    ),
    CacheRule(
        id="intel_cache",
        group="GPU и игры",
        title="Intel Shader / Graphics Cache",
        risk="Safe",
        paths=[
            r"%LOCALAPPDATA%\Intel\ShaderCache",
            r"%LOCALAPPDATA%\Intel\GPA",
        ],
        what="Кэш шейдеров встроенной графики Intel и инструментов GPA.",
        why="Остаётся от игр и видеоредакторов на ноутбуках с Intel iGPU.",
        safety="Безопасно.",
        recommend="Можно удалять.",
    ),
    CacheRule(
        id="steam_cache",
        group="GPU и игры",
        title="Steam: shadercache, depotcache, appcache (временное)",
        risk="Moderate",
        paths=[
            r"C:\Program Files (x86)\Steam\shadercache",
            r"C:\Program Files\Steam\shadercache",
            r"%PROGRAMFILES(X86)%\Steam\appcache\httpcache",
            r"%PROGRAMFILES%\Steam\appcache\httpcache",
            r"%LOCALAPPDATA%\Steam\htmlcache",
        ],
        what="Предкомпилированные шейдеры Steam (Proton/Vulkan) и HTTP-кэш магазина. Одна игра может держать 1–5 ГБ шейдеров.",
        why="Steam качает/генерирует шейдеры для каждой игры и Proton-версии.",
        safety="Умеренно: сами игры НЕ удалятся, но при следующем запуске возможна долгая фоновая компиляция шейдеров и подтормаживания.",
        recommend="Чистите, только если не играете ежедневно. Не трогайте папки common/steamapps — это сами игры.",
    ),
    CacheRule(
        id="launchers_cache",
        group="GPU и игры",
        title="Лаунчеры: Epic, GOG, Ubisoft, EA (web-кэш)",
        risk="Safe",
        paths=[
            r"%LOCALAPPDATA%\EpicGamesLauncher\Saved\webcache*",
            r"%LOCALAPPDATA%\GOG.com\Galaxy\webcache*",
            r"%LOCALAPPDATA%\Ubisoft Game Launcher\cache",
            r"%LOCALAPPDATA%\Electronic Arts\EA Desktop\cache",
            r"%LOCALAPPDATA%\Riot Games\Riot Client\UxCache",
            r"%LOCALAPPDATA%\Battle.net\Cache",
            r"%LOCALAPPDATA%\HoYoverse\*\cache",
        ],
        what="Встроенные браузеры лаунчеров (Chromium): картинки магазина, баннеры, логины.",
        why="Лаунчеры — это веб-страницы, они кэшируют магазин как браузер.",
        safety="Безопасно: разлогина обычно не происходит, просто первый запуск магазина будет чуть медленнее.",
        recommend="Можно чистить.",
    ),
    CacheRule(
        id="minecraft_cache",
        group="GPU и игры",
        title="Minecraft / CurseForge / Prism временные",
        risk="Safe",
        paths=[
            r"%APPDATA%\.minecraft\webcache*",
            r"%APPDATA%\.minecraft\logs",
            r"%APPDATA%\.minecraft\crash-reports",
            r"%LOCALAPPDATA%\CurseForge\Cache",
            r"%LOCALAPPDATA%\PrismLauncher\cache",
        ],
        what="Логи, краш-репорты и веб-кэш лаунчеров Minecraft. Миры и моды здесь НЕ лежат.",
        why="Каждый запуск пишет логи; старые версии копятся.",
        safety="Безопасно. Миры (saves) и mods не затрагиваются.",
        recommend="Логи старше недели можно удалять.",
    ),
    # ---------------------------------------------------------------- DEV
    CacheRule(
        id="npm_cache",
        group="Разработка",
        title="Node.js: npm / yarn / pnpm кэш",
        risk="Safe",
        paths=[
            r"%LOCALAPPDATA%\npm-cache",
            r"%APPDATA%\npm-cache",
            r"%LOCALAPPDATA%\Yarn\Cache",
            r"%LOCALAPPDATA%\pnpm\store",
            r"%LOCALAPPDATA%\pnpm-store",
            r"%USERPROFILE%\.npm",
            r"%USERPROFILE%\.cache\node-gyp",
        ],
        what="Скачанные tarball'ы пакетов npm/yarn/pnpm. Ускоряют повторный `npm install`.",
        why="`npm install` никогда сам не чистит кэш — за год легко 3–10 ГБ.",
        safety="Безопасно: `npm cache verify` / `pnpm store prune` делают то же самое штатно. Следующая установка просто докачает нужное.",
        recommend="Штатная команда: npm cache clean --force. Мы удаляем файлы напрямую — эффект тот же.",
    ),
    CacheRule(
        id="pip_cache",
        group="Разработка",
        title="Python: pip / uv / Poetry кэш",
        risk="Safe",
        paths=[
            r"%LOCALAPPDATA%\pip\Cache",
            r"%LOCALAPPDATA%\pip\cache",
            r"%LOCALAPPDATA%\uv\cache",
            r"%USERPROFILE%\.cache\uv",
            r"%LOCALAPPDATA%\pypoetry\Cache",
            r"%LOCALAPPDATA%\Poetry\Cache",
            r"%APPDATA%\Python\pip\cache",
        ],
        what="Кэшированные колёса (wheels) pip и uv. Ускоряют повторную установку пакетов.",
        why="pip хранит каждую скачанную версию. uv-кэш бывает 5+ ГБ у ML-разработчиков (torch, transformers).",
        safety="Полностью безопасно. Штатный аналог: `pip cache purge` и `uv cache clean`.",
        recommend="Чистить смело.",
    ),
    CacheRule(
        id="cargo_gradle_maven",
        group="Разработка",
        title="Rust / Java / Go / .NET сборочные кэши",
        risk="Moderate",
        paths=[
            r"%USERPROFILE%\.cargo\registry\cache",
            r"%USERPROFILE%\.gradle\caches\modules-2",
            r"%USERPROFILE%\.m2\repository",
            r"%LOCALAPPDATA%\NuGet\v3-cache",
            r"%USERPROFILE%\.nuget\packages",
            r"%LOCALAPPDATA%\Go\build-cache",
            r"%USERPROFILE%\go\pkg\mod\cache\download",
        ],
        what="Загруженные зависимости Cargo, Gradle, Maven, NuGet и кэш сборки Go. Без них проект всё равно соберётся — просто дольше.",
        why="Сборщики никогда не удаляют старые версии библиотек.",
        safety="Умеренно: удаление НЕ ломает исходники, но следующая сборка будет долгой (перекачивание). Папки `target/`, `build/` ваших проектов мы НЕ трогаем автоматически.",
        recommend="Чистите, если давно не собирали эти проекты. Активные проекты лучше не трогать.",
    ),
    CacheRule(
        id="docker_wsl",
        group="Разработка",
        title="Docker Desktop / WSL2 виртуальные диски (анализ)",
        risk="Advanced",
        paths=[
            r"%LOCALAPPDATA%\Docker\wsl\data\ext4.vhdx",
            r"%LOCALAPPDATA%\Docker\wsl\distro\ext4.vhdx",
            r"%LOCALAPPDATA%\Packages\*\LocalState\ext4.vhdx",
            r"%USERPROFILE%\WSL\*.vhdx",
        ],
        what="Виртуальные диски Docker и WSL2. Внутри — образы, контейнеры и Linux-файлы. Один vhdx легко весит 20–60 ГБ и НЕ уменьшается сам после `docker rmi`.",
        why="Docker не возвращает место хосту автоматически; удалённые образы остаются внутри vhdx как свободные блоки.",
        safety="Осторожно! Сам файл удалять НЕЛЬЗЯ — убьёте все контейнеры. Правильно: `docker system prune -a --volumes`, затем `wsl --shutdown` и `Optimize-VHD -Mode Full`. Мы только показываем вес и даём команды.",
        recommend="Только анализ + штатные команды Docker. Удаление файла — лишь если Docker/WSL больше не нужны.",
    ),
    CacheRule(
        id="vscode_cache",
        group="Разработка",
        title="VS Code / Cursor / JetBrains кэши",
        risk="Safe",
        paths=[
            r"%APPDATA%\Code\Cache",
            r"%APPDATA%\Code\CachedData",
            r"%APPDATA%\Code\GPUCache",
            r"%APPDATA%\Code\Crashpad",
            r"%APPDATA%\Cursor\Cache",
            r"%APPDATA%\Cursor\GPUCache",
            r"%APPDATA%\Cursor\CachedData",
            r"%LOCALAPPDATA%\JetBrains\*\caches",
            r"%LOCALAPPDATA%\JetBrains\Transient*",
        ],
        what="Chromium-кэш редакторов на Electron и индексные кэши JetBrains.",
        why="Каждый апдейт VS Code оставляет старый CachedData.",
        safety="Безопасно. Настройки и расширения лежат в другом месте и не затрагиваются.",
        recommend="Закройте редактор перед чисткой.",
    ),
    # ---------------------------------------------------------------- APPS
    CacheRule(
        id="telegram_cache",
        group="Мессенджеры и приложения",
        title="Telegram Desktop: кэш медиа",
        risk="Safe",
        paths=[
            r"%USERPROFILE%\Downloads\Telegram Desktop",
            r"%APPDATA%\Telegram Desktop\tdata\user_data\cache",
            r"%APPDATA%\Telegram Desktop\tdata\temp",
            r"%LOCALAPPDATA%\Telegram Desktop\tdata\temp",
        ],
        what="Превью фото/видео/стикеров и недокачанные файлы. Сами чаты хранятся в облаке Telegram.",
        why="Telegram кэширует всё, что вы просматривали. Активные чаты за год — это 5–20 ГБ.",
        safety="Безопасно: переписка и файлы в облаке не пропадут, докачаются заново. Папку `tdata` (ключи сессии) мы НЕ трогаем — разлогина не будет.",
        recommend="Штатно чистится и в самом Telegram: Настройки → Данные и память.",
    ),
    CacheRule(
        id="discord_cache",
        group="Мессенджеры и приложения",
        title="Discord / Slack / Teams (Electron-кэш)",
        risk="Safe",
        paths=[
            r"%APPDATA%\discord\Cache",
            r"%APPDATA%\discord\GPUCache",
            r"%APPDATA%\discord\Code Cache",
            r"%APPDATA%\discord\Crashpad",
            r"%APPDATA%\Slack\Cache",
            r"%APPDATA%\Slack\GPUCache",
            r"%APPDATA%\Slack\Code Cache",
            r"%APPDATA%\Microsoft\Teams\Cache",
            r"%APPDATA%\Microsoft\Teams\GPUCache",
            r"%APPDATA%\Microsoft\Teams\Code Cache",
            r"%LOCALAPPDATA%\Microsoft\Teams\SquirrelTemp",
            r"%APPDATA%\WhatsApp\Cache",
            r"%APPDATA%\WhatsApp\GPUCache",
            r"%LOCALAPPDATA%\Viber\cache",
        ],
        what="Chromium-кэши Electron-мессенджеров: аватары, превью, баннеры, шрифты.",
        why="Каждый запуск подгружает медиа, которое оседает в Cache и Code Cache.",
        safety="Безопасно. Сессии и чаты не затрагиваются. Закройте мессенджер перед чисткой.",
        recommend="Можно чистить.",
    ),
    CacheRule(
        id="browser_cache",
        group="Мессенджеры и приложения",
        title="Браузеры: Chrome / Edge / Firefox / Brave / Opera",
        risk="Moderate",
        paths=[
            r"%LOCALAPPDATA%\Google\Chrome\User Data\*\Cache",
            r"%LOCALAPPDATA%\Google\Chrome\User Data\*\Code Cache",
            r"%LOCALAPPDATA%\Google\Chrome\User Data\*\GPUCache",
            r"%LOCALAPPDATA%\Google\Chrome\User Data\*\Service Worker\CacheStorage",
            r"%LOCALAPPDATA%\Microsoft\Edge\User Data\*\Cache",
            r"%LOCALAPPDATA%\Microsoft\Edge\User Data\*\Code Cache",
            r"%LOCALAPPDATA%\Microsoft\Edge\User Data\*\GPUCache",
            r"%LOCALAPPDATA%\BraveSoftware\Brave-Browser\User Data\*\Cache",
            r"%LOCALAPPDATA%\BraveSoftware\Brave-Browser\User Data\*\Code Cache",
            r"%LOCALAPPDATA%\Opera Software\Opera Stable\Cache",
            r"%LOCALAPPDATA%\Vivaldi\User Data\*\Cache",
            r"%APPDATA%\Mozilla\Firefox\Profiles\*\cache2",
            r"%LOCALAPPDATA%\Mozilla\Firefox\Profiles\*\cache2",
        ],
        what="Кэш страниц, картинки, видео-превью и Service Worker хранилища. У активных пользователей — 2–8 ГБ.",
        why="Браузер ускоряет повторное открытие сайтов ценой места.",
        safety="Умеренно: пароли и закладки НЕ трогаем (они в других файлах). Но выход из части сайтов возможен, первый визит будет медленнее. Cookies и историю мы НЕ чистим принципиально.",
        recommend="Закройте браузер. Чистите Cache/Code Cache, но не трогайте Local Storage без нужды.",
    ),
    CacheRule(
        id="spotify_cache",
        group="Мессенджеры и приложения",
        title="Spotify / Yandex Music / iTunes медиа-кэш",
        risk="Safe",
        paths=[
            r"%LOCALAPPDATA%\Spotify\Storage",
            r"%LOCALAPPDATA%\Spotify\Data",
            r"%APPDATA%\Spotify\Cache",
            r"%LOCALAPPDATA%\Packages\*Spotify*\LocalCache",
            r"%LOCALAPPDATA%\YandexMusic\cache",
        ],
        what="Скачанные треки и обложки для офлайн-работы. У меломанов — 5–15 ГБ.",
        why="Стриминг кэширует каждый прослушанный трек.",
        safety="Безопасно: плейлисты в облаке, треки перекачаются. Офлайн-треки придётся скачать заново.",
        recommend="Если слушаете онлайн — чистите смело.",
    ),
    CacheRule(
        id="office_cache",
        group="Мессенджеры и приложения",
        title="Microsoft Office: кэш документов и обновления",
        risk="Safe",
        paths=[
            r"%LOCALAPPDATA%\Microsoft\Office\*\OfficeFileCache",
            r"%LOCALAPPDATA%\Microsoft\Office\OTele",
            r"%LOCALAPPDATA%\Microsoft\OneNote\*\cache",
        ],
        what="Черновики OneDrive-синхронизации и телеметрия Office.",
        why="Office держит локальные копии облачных файлов для быстрого открытия.",
        safety="Безопасно при закрытом Office и завершённой синхронизации OneDrive (проверьте зелёную галку в трее).",
        recommend="Закройте Word/Excel перед чисткой.",
    ),
    CacheRule(
        id="adobe_cache",
        group="Мессенджеры и приложения",
        title="Adobe / DaVinci / Blender превью-кэш",
        risk="Moderate",
        paths=[
            r"%APPDATA%\Adobe\Common\Media Cache Files",
            r"%APPDATA%\Adobe\Common\Peak Files",
            r"%LOCALAPPDATA%\Blackmagic Design\DaVinci Resolve\Cache",
            r"%APPDATA%\Blender Foundation\Blender\*\cache",
            r"%LOCALAPPDATA%\GIMP\*\tmp",
        ],
        what="Пиковые формы аудиодорожек, превью рендеров и миниатюры. У монтажёров — десятки ГБ.",
        why="Редакторы генерируют превью для плавного скролла таймлайна.",
        safety="Умеренно: проекты НЕ пострадают, но превью пересоздадутся долго при следующем открытии.",
        recommend="Чистите завершённые проекты; активный проект лучше не трогать.",
    ),
    CacheRule(
        id="zoom_obs_cache",
        group="Мессенджеры и приложения",
        title="Zoom / OBS / Skype логи и записи-кэш",
        risk="Safe",
        paths=[
            r"%APPDATA%\Zoom\logs",
            r"%APPDATA%\Zoom\data\Cache",
            r"%APPDATA%\obs-studio\logs",
            r"%APPDATA%\obs-studio\crashes",
            r"%APPDATA%\Skype\Cache",
            r"%LOCALAPPDATA%\Microsoft\OneDrive\logs",
        ],
        what="Логи звонков и падений. Сами записи Zoom/OBS мы НЕ трогаем.",
        why="Каждый звонок пишет мегабайты логов.",
        safety="Безопасно.",
        recommend="Можно удалять.",
    ),
    # ---------------------------------------------------------------- WINDOWS
    CacheRule(
        id="windows_temp",
        group="Windows и обновления",
        title="Временные файлы Windows и пользователя",
        risk="Safe",
        paths=[
            r"%TEMP%",
            r"%TMP%",
            r"C:\Windows\Temp",
            r"%LOCALAPPDATA%\Temp",
            r"C:\Windows\Prefetch",
        ],
        what="TEMP-папки: распаковки установщиков, остатки обновлений, превью. Prefetch — ускорение запуска программ.",
        why="Программы обязаны сами чистить TEMP, но 90% этого не делают.",
        safety="Безопасно при закрытых установщиках. Файлы, занятые запущенными программами, мы пропускаем автоматически (PermissionError — это нормально). Prefetch чистить необязательно, но безвредно.",
        recommend="Перезагрузитесь и чистите — занятых файлов будет меньше.",
    ),
    CacheRule(
        id="update_cache",
        group="Windows и обновления",
        title="Кэш Центра обновлений и доставки",
        risk="Moderate",
        paths=[
            r"C:\Windows\SoftwareDistribution\Download",
            r"C:\Windows\SoftwareDistribution\DataStore\Logs",
            r"%PROGRAMDATA%\Microsoft\Windows\DeliveryOptimization\Cache",
            r"C:\Windows\Installer\$PatchCache$",
        ],
        what="Скачанные установщики обновлений Windows и кэш Delivery Optimization (раздача обновлений другим ПК).",
        why="После установки патчей их копии лежат мёртвым грузом, иногда по 5–10 ГБ.",
        safety="Умеренно: чистить только если последние обновления успешно установились и перезагрузка выполнена. Службу wuauserv останавливать не обязательно — занятые файлы пропустим.",
        recommend="Не чистите в день большого обновления (например, 24H2). Требуется место для отката — Windows сама удалит через 10 дней.",
    ),
    CacheRule(
        id="crash_dumps",
        group="Windows и обновления",
        title="Crash Dumps, Minidump, MEMORY.DMP",
        risk="Safe",
        paths=[
            r"%LOCALAPPDATA%\CrashDumps",
            r"%LOCALAPPDATA%\CrashDumps\*\*",
            r"C:\Windows\Minidump",
            r"C:\Windows\MEMORY.DMP",
            r"C:\Windows\LiveKernelReports",
            r"%APPDATA%\Microsoft\Windows\WER\ReportQueue",
            r"%APPDATA%\Microsoft\Windows\WER\Temp",
            r"%PROGRAMDATA%\Microsoft\Windows\WER\ReportQueue",
        ],
        what="Снимки упавших программ и синих экранов (BSOD) для разработчиков. MEMORY.DMP бывает размером с ОЗУ (16–32 ГБ!).",
        why="Каждый краш пишет дамп; нужны они только разработчикам для отладки.",
        safety="Безопасно, если вы не расследуете конкретное падение прямо сейчас. Систему не затрагивает.",
        recommend="Один свежий дамп можно оставить для диагностики, остальное — в корзину.",
    ),
    CacheRule(
        id="thumb_icon_cache",
        group="Windows и обновления",
        title="Эскизы проводника и кэш иконок/шрифтов",
        risk="Safe",
        paths=[
            r"%LOCALAPPDATA%\Microsoft\Windows\Explorer\thumbcache_*.db",
            r"%LOCALAPPDATA%\Microsoft\Windows\Explorer\iconcache_*.db",
            r"%LOCALAPPDATA%\Microsoft\Windows\Fonts\*.cache",
            r"%LOCALAPPDATA%\Microsoft\Windows\Caches",
        ],
        what="Миниатюры фото/видео и иконки для быстрого отображения в Проводнике.",
        why="Пересоздаются автоматически, старые записи не чистятся.",
        safety="Безопасно: первое открытие папки с фото будет чуть медленнее, пока эскизы строятся заново.",
        recommend="Можно чистить.",
    ),
    CacheRule(
        id="windows_logs",
        group="Windows и обновления",
        title="Логи CBS, DISM и установки Windows",
        risk="Safe",
        paths=[
            r"C:\Windows\Logs\CBS",
            r"C:\Windows\Logs\DISM",
            r"C:\Windows\Logs\WindowsUpdate",
            r"C:\Windows\Panther",
            r"C:\$Windows.~BT",
            r"C:\$Windows.~WS",
        ],
        what="Гигабайты текстовых логов проверки системных файлов (CBS.log бывает 2–5 ГБ!) и остатки неудачных обновлений.",
        why="CBS.log растёт бесконечно при повреждённых компонентах; $Windows.~BT — файлы отката после обновления.",
        safety="Безопасно, кроме периода прямо во время обновления. Если CBS.log снова растёт — это симптом, стоит выполнить `sfc /scannow`.",
        recommend="Чистите после успешного обновления.",
    ),
    CacheRule(
        id="windows_old",
        group="Windows и обновления",
        title="Windows.old — предыдущая версия Windows",
        risk="Advanced",
        paths=[
            r"C:\Windows.old",
            r"C:\$WinREAgent",
        ],
        what="Полная копия старой Windows для отката в течение 10 дней после крупного обновления. Весит 15–30 ГБ.",
        why="Создаётся при обновлении 22H2→23H2 и подобных.",
        safety="Осторожно: после удаления откат невозможен без переустановки. Чистите только если новая версия работает стабильно 3+ дня.",
        recommend="Штатно удаляется через «Очистку диска → Очистить системные файлы». Мы отправляем в корзину — для такого объёма убедитесь, что на диске хватает места для корзины, иначе используйте перманентное удаление.",
    ),
    CacheRule(
        id="hiber_page",
        group="Windows и обновления",
        title="Гибернация (hiberfil.sys) и своп (анализ)",
        risk="Advanced",
        paths=[
            r"C:\hiberfil.sys",
            r"C:\pagefile.sys",
            r"C:\swapfile.sys",
        ],
        what="hiberfil.sys = образ ОЗУ для гибернации (40% от RAM, ~6–13 ГБ). pagefile.sys = виртуальная память. Удалять их как файлы НЕЛЬЗЯ.",
        why="Создаются ядром Windows при загрузке.",
        safety="Только штатные команды: `powercfg -h off` отключает гибернацию и удаляет hiberfil.sys; pagefile трогать не рекомендуем вообще (риск BSOD и тормозов). Мы показываем размер и даём кнопку копирования команды.",
        recommend="Ноутбук с SSD и быстрым стартом — гибернацию можно отключить. Десктоп с 32 ГБ RAM — тоже.",
    ),
    CacheRule(
        id="recycle_defender",
        group="Windows и обновления",
        title="Корзина и кэш Защитника Windows",
        risk="Moderate",
        paths=[
            r"C:\$Recycle.Bin",
            r"%PROGRAMDATA%\Microsoft\Windows Defender\Scans\History",
            r"%PROGRAMDATA%\Microsoft\Windows Defender\Support",
        ],
        what="Удалённые файлы в корзине и история сканирований Defender.",
        why="Корзина не очищается сама; история Defender копит логи.",
        safety="Умеренно: проверьте корзину перед очисткой — восстановление будет невозможно. Кэш Defender безопасен.",
        recommend="Откройте корзину и убедитесь, что там нет нужного.",
    ),
    CacheRule(
        id="delivery_store",
        group="Windows и обновления",
        title="Доставка Store, DirectX и прочие мелкие кэши",
        risk="Safe",
        paths=[
            r"%LOCALAPPDATA%\Packages\Microsoft.WindowsStore_*\LocalState\Cache",
            r"%LOCALAPPDATA%\Microsoft\Windows\INetCache",
            r"%LOCALAPPDATA%\Microsoft\Windows\INetCookies",
            r"%LOCALAPPDATA%\ConnectedDevicesPlatform",
            r"%APPDATA%\Adobe\Acrobat\DC\Cache",
            r"%LOCALAPPDATA%\Notion\Cache",
            r"%APPDATA%\Notion\Cache",
            r"%LOCALAPPDATA%\Figma\Cache",
            r"%APPDATA%\Figma\Cache",
        ],
        what="Мелкие веб-кэши Store-приложений, Figma, Notion, Acrobat.",
        why="Каждое Electron/Chromium-приложение тащит свой Cache.",
        safety="Безопасно.",
        recommend="Чистить скопом.",
    ),
]


def get_rule(rule_id: str) -> CacheRule | None:
    for r in RULES:
        if r.id == rule_id:
            return r
    return None


def groups() -> list[str]:
    seen: list[str] = []
    for r in RULES:
        if r.group not in seen:
            seen.append(r.group)
    return seen
